---
env:
  global:
    - REPO_DIR=bezier
    - BUILD_COMMIT=9d2cc51a18bd2ec8e3a17d576e907e306310d0be
    - BUILD_DEPENDS="numpy"
    - TEST_DEPENDS="--requirement bezier/scripts/requirements.txt"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - ENV_VARS_PATH="travis/env_vars.sh"
    - CONFIG_PATH="travis/config.sh"

addons:
  homebrew:
    packages:
      - gcc # For `gfortran`

language: python
python: 3.7
sudo: required
dist: bionic
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: osx
      osx_image: xcode11.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode11.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      osx_image: xcode11.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - clean_code ${REPO_DIR} ${BUILD_COMMIT}
  - build_wheel ${REPO_DIR} ${PLAT}

script:
  - install_run ${PLAT}

after_success:
  # Make a virtual environment for `gsutil`
  - python -m pip install --upgrade pip virtualenv
  - python -m virtualenv gsutil-env
  - gsutil-env/bin/pip install gsutil

  # Set up the `boto` configuration for `gsutil`. BOTO_CONFIG must be set
  # before calling `populate_boto.py`
  - export BOTO_CONFIG=${TRAVIS_BUILD_DIR}/.boto
  - gsutil-env/bin/python ${TRAVIS_BUILD_DIR}/populate_boto.py

  # Decrypt `key.json` for use to upload to GCS.
  - |
    openssl aes-256-cbc \
      -K ${encrypted_02a99c88fc32_key} \
      -iv ${encrypted_02a99c88fc32_iv} \
      -in travis/key.json.enc \
      -out key.json -d

  # Upload the wheel to GCS.
  - |
    gsutil-env/bin/gsutil cp \
      ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl \
      gs://${GCS_BUCKET}
